### ISSUE TITLE
Probably some issues with newest python 3.13 on Home Assistant 2024.12

### ISSUE THREAD

**Issue by davralin** [theneweinstein/pysomneo#19]
Hi,
from bootup:
````
2024-12-05 21:02:17.818 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration somneo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-05 21:02:23.524 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/ppadb/device.py:34: SyntaxWarning: invalid escape sequence '\s'
  INSTALL_RESULT_PATTERN = "(Success|Failure|Error)\s?(.*)"

2024-12-05 21:02:23.526 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/ppadb/command/transport/__init__.py:95: SyntaxWarning: invalid escape sequence '\['
  result_pattern = "^\[([\s\S]*?)\]: \[([\s\S]*?)\]\r?$"

2024-12-05 21:02:23.531 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/ppadb/plugins/device/utils.py:35: SyntaxWarning: invalid escape sequence '\s'
  pattern = "ACTIVITY\s([\w\.]+)/([\w\.]+)\s[\w\d]+\spid=([\d]+)"

2024-12-05 21:02:23.531 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/ppadb/plugins/device/utils.py:48: SyntaxWarning: invalid escape sequence '\s'
  total_meminfo_re = re.compile('\s*TOTAL\s*(?P<pss>\d+)'

2024-12-05 21:02:23.531 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/ppadb/plugins/device/utils.py:49: SyntaxWarning: invalid escape sequence '\s'
  '\s*(?P<private_dirty>\d+)'

2024-12-05 21:02:23.531 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/ppadb/plugins/device/utils.py:50: SyntaxWarning: invalid escape sequence '\s'
  '\s*(?P<private_clean>\d+)'

2024-12-05 21:02:23.531 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/ppadb/plugins/device/utils.py:51: SyntaxWarning: invalid escape sequence '\s'
  '\s*(?P<swapped_dirty>\d+)'

2024-12-05 21:02:23.531 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/ppadb/plugins/device/utils.py:52: SyntaxWarning: invalid escape sequence '\s'
  '\s*(?P<heap_size>\d+)'

2024-12-05 21:02:23.531 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/ppadb/plugins/device/utils.py:53: SyntaxWarning: invalid escape sequence '\s'
  '\s*(?P<heap_alloc>\d+)'

2024-12-05 21:02:23.531 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/ppadb/plugins/device/utils.py:54: SyntaxWarning: invalid escape sequence '\s'
  '\s*(?P<heap_free>\d+)')

2024-12-05 21:02:23.531 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/ppadb/plugins/device/utils.py:85: SyntaxWarning: invalid escape sequence '\d'
  pattern = "userId=([\d]+)"

2024-12-05 21:02:23.531 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/ppadb/plugins/device/utils.py:102: SyntaxWarning: invalid escape sequence '\d'
  pattern = "versionName=([\d\.]+)"

2024-12-05 21:02:23.533 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/ppadb/plugins/device/wm.py:12: SyntaxWarning: invalid escape sequence '\s'
  SIZE_RE = 'Physical size:\s([\d]+)x([\d]+)'

2024-12-05 21:02:23.534 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/ppadb/plugins/device/traffic.py:36: SyntaxWarning: invalid escape sequence '\d'
  pattern = "userId=([\d]+)"

2024-12-05 21:02:23.536 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/ppadb/plugins/device/cpustat.py:90: SyntaxWarning: invalid escape sequence '\s'
  "cpu\s+([\d]+)\s([\d]+)\s([\d]+)\s([\d]+)\s([\d]+)\s([\d]+)\s([\d]+)\s([\d]+)\s([\d]+)\s([\d]+)\s")

2024-12-05 21:02:26.539 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'somneo': Unable to import component: No module named 'pysomneo'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1034, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1014, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1074, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/somneo/__init__.py", line 14, in <module>
    from pysomneo import SOURCES, Somneo
ModuleNotFoundError: No module named 'pysomneo'
````

**Comment by Akruidenberg** [comment]
Would love to buy a smartsleep. Hopefully this will be fixed.

**Comment by davralin** [comment]
Wasn't an issue anyway, just required a complete uninstall-reinstall of the ingreation.
