### ISSUE TITLE
Fetching sensor data often times out

### ISSUE THREAD

**Issue by thomwiggers** [theneweinstein/pysomneo#8]
I've started to run into the problem that the fetching of sensor data from the `wusrd` endpoint times out most of the time. 

Interestingly enough, if I do this in the Python shell using `requests.get()`, it _never_ times out. But if I use the `Somneo._session` object then it times out often. So I think the Somneo device doesn't like Session very much.

## Full stacktrace
```py
>>> s._get('wusrd')
Connection to Somneo timed out.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/local/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.10/ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.10/ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.10/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='192.168.3.103', port=443): Read timed out. (read timeout=20)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/pysomneo/__init__.py", line 96, in _get
    return self._internal_call('GET', url, None, payload)
  File "/usr/local/lib/python3.10/site-packages/pysomneo/__init__.py", line 77, in _internal_call
    r = self._session.request(method, url, verify=False, timeout=20, **args)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='192.168.3.103', port=443): Read timed out. (read timeout=20)
```

**Comment by thomwiggers** [comment]
After further testing, I don't think Session is the cause, but somehow outside of my HA container, this error pops up very often, while outside of the container it's much more rare. I'm going to do some more testing.

**Comment by thomwiggers** [comment]
If I run the following snippet of code in a `python:alpine` container, it works if I use the normal Docker networking, but if I use `--network=host` like the homeassistant container is set up, then it just takes forever:

```python
s = Somneo(HOST)
s.fetch_data()
```

I wonder if we're hitting a bug in Python here.

**Comment by thomwiggers** [comment]
If I run the following snippet of code in a `python:alpine` container, it works if I use the normal Docker networking, but if I use `--network=host` like the homeassistant container is set up, then it just takes forever:

```python
s = Somneo(HOST)
s.fetch_data()
```

I wonder if we're hitting a bug in Python here.

**Comment by thomwiggers** [comment]
I also have the impression that if I leave the `Somneo` object to sit around for a minute or so, the thing hangs. If I replace the `Somneo._session` object, then the `fetch_data` becomes more responsive again. So I also wonder if the TLS implementation in the Somneo device lets the connection time out in an incorrect manner (not sending the correct TLS connection close alert).

**Comment by thomwiggers** [comment]
re: the latter: the Somneo device's TLS implementation definitely closes TLS connections incorrectly:

```
openssl s_client -crlf HOST:443
GET<enter><enter>

HTTP/1.1 400 Bad Request
Content-Length: 29
Content-Type: application/json
Strict-Transport-Security: max-age=31536000

{ "error": "Not understood" }
<wait>
40E701C5227F0000:error:0A000126:SSL routines:ssl3_read_n:unexpected eof while reading:ssl/record/rec_layer_s3.c:320:
```

I think `requests` _should_ use keep-alive though: https://requests.readthedocs.io/en/latest/user/advanced/?highlight=keep%20alive#keep-alive

**Comment by thomwiggers** [comment]
Also interesting: it only seems to support a single TLS connection at a time. If I connect in two different terminals, the first connection gets kicked out once the second one connects.

**Comment by sandervspl** [comment]
Sorry to bump this thread. I'm also experiencing constant timeouts. Even the SleepMapper app is timing out on requests to my wakeup light after I send my own requests.  Is this something you have encountered? Anything I need to look out for when using this API?

**Comment by theneweinstein** [comment]
I recently rewrote the code and removed the options to disable sessions (no idea why). I added this option again. Since I don't experience these timeouts, I cannot test properly. I released a beta version of the Somneo component (v2024.2.2b2) to is able to disable the TLS session via the configure button. Let me know if this helps.

**Comment by thomwiggers** [comment]
I've not really been paying attention to this lately, but I noticed that with the current version that I have installed, v6.0.0beta3, my Somneo stats appears to get consistently collected.

I will update and report back.

**Comment by thomwiggers** [comment]
It seems to be working reliably now, for version 2024.2.2b2 with TLS connection reuse turned on. I have no idea what changed or by what voodoo magic this used to cause or doesn't cause issues anymore.

**Comment by VictorLabeille** [comment]
Disclaimer : My Somneo is a HF3671/01 model swverwifi 2.2.5 with the firmware pkgver 30406 so the results I got (by testing with a LAN host) and my conclusions may not be the same on other Somneos.
  
From my tests, your 2022 observations were right : only one TLS connection at once and TLS is badly closed by the Somneo. I get the same "unexpected eof while reading" as you.
Here is a recap of dying requests when parallelizing :
  
| Number of simultaneous requests | Success                     | Main error                            |
| ------------------------------- | -------------------------- | ------------------------------------- |
| 1                               | 63/63                      | —                                     |
| 2                               | 33/60 (11/20 three times)  | `RemoteDisconnected` ×9 per set       |
| 3                               | 21/63 (6, 8, 7)            | `RemoteDisconnected` + `SSLEOFError`  |
  
The rate follows ~1/N. The free heap (`/di/v1/products/0/mem`) stays at 24 824 bytes during every error, it's not a lack of memory.

From what @sandervspl is saying above, even SleepMapper timeout when he sends his own requests. So the problem looks like it isn't pysomneo but a constraint from the Somneo that any library needs to account for.

Raw concurrency doesn't look to be the daily problem. The main trigger is a request that arrives while another is being executed. I tested a thread with 7 consecutives reads (like fetch_data) and another send 1 request randomly within the 7 reads timeframe.
The result : the isolated request is always a sucess while the refresh losses some reads (it doesn't without concurrency).


| Request type                | Responses                                      |
| --------------------------- | ---------------------------------------------- |
| isolated request            | 20/20                                          |
| refresh reads               | 128/140 (11 RemoteDisconnected, 1 SSLEOFError) |
| damaged refresh             | 10/20 - half                                   |
| witness without concurrency | 70/70                                          |

My theory : **The Somneo answer to the incoming/new request and abandons the one it was working on**.
The problem is hitting on the automatic polling (data collection) from the container, not the handmade request.

I've looked into how the session is managed today :
```python
HTTPAdapter(pool_connections=5, pool_maxsize=5,
            max_retries=Retry(total=3, backoff_factor=2.0, ...),
            pool_block=False)
```
This allows up to five simultaneous conections towards the Somneo that only serves one. And `pool_block=False` looks like it allows to bypass the limit and open even more connections when the pool is full.

The branch `improve/reduce-timeout-errors` (PR #23, merge in may 2026) treats the symptomes but not really the cause. Reading it, I saw that this is also where the pool went from 1 to 5 : "Increase connection pool size from 1 to 5 to avoid connection exhaustion". So what I measured below includes going back to the pool size you had before that PR, and I wanted to see what the change actually bought.
Here is a comparison between three configurations :

| Configuration                    | Success | 3 runs               | Worst request |
| -------------------------------- | ------- | -------------------- | ------------- |
| `pool=5, block=False` (current)  | 63/63   | 16.0 · 16.1 · 17.8 s | **17 552 ms** |
| `pool=1, block=True`             | 63/63   | 1.4 · 3.3 · 3.6 s    | 2 645 ms      |
| `pool=1, block=True`, no retries | 63/63   | 1.4 · 1.6 · 1.9 s    | 936 ms        |

The success rate isn't moving but the current configuration is slower (ten times), median latency : 1040ms to 120ms. So going from 1 to 5 didn't buy any success, it only bought latency : against a device that serves one connection at a time, a bigger pool only means more requests killing each other.

To be clear, I don't think the pool size was the real problem : `pool_maxsize=1` alone never serialized anything, because `pool_block=False` lets urllib3 open connections outside of the pool anyway. The missing piece is `pool_block=True`, which was never in the code. And it's also what answers the exhaustion you were avoiding : with the pool blocking, the calls queue instead of opening a new connection, so nothing is exhausted, 63/63 in every configuration I ran.

Imo, the fix is to block the pool at one blocking connection to let urllib3 serialize himself without any lock nor refactor : `pool_connections=1, pool_maxsize=1, pool_block=True`

I have also liiked and tested the branch `ai-improvements` (that looked to be where 6.0.0 is headed). To this day, this connector allows `TCPConnector(ssl=False)` without limit and aiohttp defaults to 100 so 20 times more that the current master. So since concurrency really looks to be the problem with the Somneo, the synchronous current version might accidently protect the request. Moving to an asyncronous communication might worsen the issue.

I tried N `fetch_data(force_slow_refresh=True)` in `gather` on a shared instance :

| Connector                           | 2 tasks         | 3 tasks        | 6 tasks           |
| ----------------------------------- | --------------- | -------------- | ----------------- |
| `TCPConnector(ssl=False)` — current | 6/6, 9.8 s      | 9/9, 17.1 s    | **16/18**, 22.1 s |
| `+ limit=1`                         | 6/6, **0.9 s**  | 9/9, **1.4 s** | **18/18, 2.8 s**  |
| `+ limit=1, force_close=True`       | **5/6**, 14.2 s | 9/9, 24.5 s    | **9/18**, 24.4 s  |

Adding `limit=1` (line two) divide the response time by 11 and don't lose any packet even at 6 tasks (where the branch losses 2 calls).
Oddly enough, adding `force_close=True` (destroying the TLS connection) losses about half of the packets. So serializing without closing the connection looks to be the right way here (`TCPConnector(ssl=False, limit=1)`).

@thomwiggers I didn't reproduced your `ReadTimeout` error but :
My theory why you have this error and I don't is that the reading request is re-sent and that turn into waiting.
I've tested N threads calling `fetch_data(force_slow_refresh=True)` on a shared instance, like the coordinator does :

| Threads | Success | Median | Worst call |
| --- | --- | --- | --- |
| 2 | 6/6 | 8 203 ms | 10 593 ms |
| 3 | 9/9 | 10 481 ms | 29 030 ms |
| 4 | 12/12 | 10 331 ms | 39 474 ms |
| 6 | 18/18 | 18 946 ms | **93 622 ms** |

As you can see, no error but a fetch_data() take up to 94 seconds. I think in 2022 there wasn't any retry loop which convert the errors in wait.
My other theory on the mystery fix is that the voodoo magic is actually the reuse of the TLS connection. From my measurements, a new connection has a median of 516ms and a reused one has 36ms.

Few things to note : my Somneo and your 2022 firmware probably aren't the same and I couldn't reproduce your second problem where the Somneo object "hangs" after a minute of inactivity. I got 12/12 success at 10, 30, 60 and 90 seconds.
I can't say anything about your `--network=host` remark.

In the end, I think your concurrency comes from `SomneoCoordinator._async_update` on the [HA integration](https://github.com/theneweinstein/somneo) side. Since july 2022 (commit d698a6f) it checks if the lock is free without taking it. Here is the snippet :
  
```python
async def _async_update(self) -> dict:
    """Fetch the latest data."""
    if self.state_lock.locked():
        return self.data or {}
```
So a user action coming during the refresh finds the lock free.

All my tests and tests' data is available here : https://github.com/VictorLabeille/Somneo-Scraper/tree/main/probes
It's good to note that I didn't reproduce your exact error tho.  

As I see it, there are two ways to fix this :
- In the HA integration : make the reading route acquire the lock, it changes the behavior from jumping to waiting
- In the library : a serialization guarantee that protects every consumer.
I personally prefer fixing at least the library and the integration after. Here is the recap of the fixes :

| Branch                      | Fix                                                                |
| --------------------------- | ------------------------------------------------------------------ |
| `master` (requests)         | `HTTPAdapter(pool_connections=1, pool_maxsize=1, pool_block=True)` |
| `ai-improvements` (aiohttp) | `TCPConnector(ssl=False, limit=1)`                                 |

I can open the PR on whichever you prefer @theneweinstein

**Comment by theneweinstein** [comment]
Hi Victor, thank you for all this work, I'm really glad we seem to get to a real solution! I'm on holiday now, so I did not look into all details, but I agree with you that a fix in the library is the best way to go. Let's focus the work on newest version (ai-improvements). I'm now testing this latest version on my instance, so far it is running fine (except the time outs), so I hope to release it somewhere this month.

**Comment by VictorLabeille** [comment]
Hi thanks for answering in such a short time :)
Duly noted on my side : my PRs will be on ai-improvements (no extra cost for me I've already worked/tested it). The timeouts you are experiencing should disappear with the fix above ! (they did in my testings)
I should send the PR this week but I'll send first an unrelated one about a value in STATUS (`wusts`).
